/*
 * hardware.h
 *
 *  Created on: Feb 29, 2020
 *      Author: marcin
 */

#ifndef HARDWARE_H_
#define HARDWARE_H_

#define BUZZER_PORT GPIOB
#define BUZZER_PIN GPIO_PIN_6

//buttons

#define BUTTON_1_PORT GPIOC
#define BUTTON_1_PIN GPIO_PIN_10

#define BUTTON_2_PORT GPIOC
#define BUTTON_2_PIN GPIO_PIN_11

#define BUTTON_3_PORT GPIOC
#define BUTTON_3_PIN GPIO_PIN_12

#define BUTTON_4_PORT GPIOD
#define BUTTON_4_PIN GPIO_PIN_2

//spi radio

#define RADIO_SDN_PORT GPIOA
#define RADIO_SDN_PIN GPIO_PIN_2

#define RADIO_INT_PORT GPIOA
#define RADIO_INT_PIN GPIO_PIN_3

#define RADIO_CS_PORT GPIOA
#define RADIO_CS_PIN GPIO_PIN_4

#define RADIO_SCK_PORT GPIOA
#define RADIO_SCK_PIN GPIO_PIN_5

#define RADIO_MISO_PORT GPIOA
#define RADIO_MISO_PIN GPIO_PIN_6

#define RADIO_MOSI_PORT GPIOA
#define RADIO_MOSI_PIN GPIO_PIN_7


//lcd
#define LCD_COM0_PORT GPIOA
#define LCD_COM0_PIN GPIO_PIN_8

#define LCD_COM1_PORT GPIOA
#define LCD_COM1_PIN GPIO_PIN_9

#define LCD_COM2_PORT GPIOA
#define LCD_COM2_PIN GPIO_PIN_10

#define LCD_COM3_PORT GPIOB
#define LCD_COM3_PIN GPIO_PIN_9

#define LCD_VLCD1_PORT GPIOB
#define LCD_VLCD1_PIN  GPIO_PIN_2

#define LCD_VLCD2_PORT GPIOB
#define LCD_VLCD2_PIN  GPIO_PIN_12

#define LCD_VLCD3_PORT GPIOB
#define LCD_VLCD3_PIN  GPIO_PIN_0

#define LCD_SEG7_PORT GPIOB
#define LCD_SEG7_PIN GPIO_PIN_3

#define LCD_SEG8_PORT GPIOB
#define LCD_SEG8_PIN GPIO_PIN_4

#define LCD_SEG9_PORT GPIOB
#define LCD_SEG9_PIN GPIO_PIN_5

#define LCD_SEG10_PORT GPIOB
#define LCD_SEG10_PIN GPIO_PIN_10

#define LCD_SEG11_PORT GPIOB
#define LCD_SEG11_PIN GPIO_PIN_11

#define LCD_SEG13_PORT GPIOB
#define LCD_SEG13_PIN GPIO_PIN_13

#define LCD_SEG14_PORT GPIOB
#define LCD_SEG14_PIN GPIO_PIN_14

#define LCD_SEG15_PORT GPIOB
#define LCD_SEG15_PIN GPIO_PIN_15

#define LCD_SEG16_PORT GPIOB
#define LCD_SEG16_PIN GPIO_PIN_8

#define LCD_SEG17_PORT GPIOA
#define LCD_SEG17_PIN GPIO_PIN_15

#define LCD_SEG22_PORT GPIOC
#define LCD_SEG22_PIN GPIO_PIN_4

#define LCD_SEG23_PORT GPIOC
#define LCD_SEG23_PIN GPIO_PIN_5

#define LCD_SEG24_PORT GPIOC
#define LCD_SEG24_PIN GPIO_PIN_6

#define LCD_SEG25_PORT GPIOC
#define LCD_SEG25_PIN GPIO_PIN_7

#define LCD_SEG26_PORT GPIOC
#define LCD_SEG26_PIN GPIO_PIN_8

#define LCD_SEG27_PORT GPIOC
#define LCD_SEG27_PIN GPIO_PIN_9

#endif /* HARDWARE_H_ */
